### model
model_name_or_path: /workspace/mnt/storage/yangdecheng@supremind.com/ydc-wksp-llm3-data/train_models/qwen2_7b_sft_2

### method
stage: rm
do_train: true
finetuning_type: lora
lora_target: v_proj,q_proj,up_proj
lora_rank: 16
lora_dropout: 0.7

### dataset
dataset: importance_stock_reward_v1
template: alpaca
cutoff_len: 4096
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2-7b/lora/sft/qwen2_7b_rm_2/
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
